#!/usr/bin/env python3
"""
Generate Secrets Utility

This utility generates cryptographically secure random values for JWT keys,
passwords, and other security-sensitive values needed for deployment.

Usage:
    python scripts/generate_secrets.py [--type TYPE] [--length LENGTH]

Options:
    --type: Type of secret to generate (jwt-key, password, api-key, all)
    --length: Length for password generation (default: 16)
"""

import argparse
import sys
from pathlib import Path

# Add the backend directory to the Python path
backend_dir = Path(__file__).parent.parent
sys.path.insert(0, str(backend_dir))

from app.core.security import generate_secret_key, generate_password


def generate_jwt_key():
    """Generate a JWT secret key."""
    key = generate_secret_key()
    print(f"JWT_SECRET_KEY={key}")
    return key


def generate_admin_password(length=16):
    """Generate an admin password."""
    password = generate_password(length)
    print(f"INITIAL_ADMIN_PASSWORD={password}")
    return password


def generate_api_key():
    """Generate an API key."""
    from app.core.security import generate_api_key

    plain_key, _ = generate_api_key()
    print(f"API_KEY={plain_key}")
    return plain_key


def generate_all():
    """Generate all types of secrets."""
    print("# DocTranslator Security Secrets")
    print("# Generated by generate_secrets.py")
    print("# Copy these to your .env file or Railway environment variables")
    print()

    print("# JWT Authentication")
    jwt_key = generate_jwt_key()
    print()

    print("# Initial Admin User")
    admin_password = generate_admin_password(16)
    print("INITIAL_ADMIN_EMAIL=admin@yourdomain.com")
    print("INITIAL_ADMIN_NAME=System Administrator")
    print()

    print("# API Key (for testing)")
    api_key = generate_api_key()
    print()

    print("# Additional Security Settings")
    print("BCRYPT_ROUNDS=12")
    print("PASSWORD_MIN_LENGTH=8")
    print("API_KEY_LENGTH=32")
    print("API_KEY_DEFAULT_EXPIRY_DAYS=90")
    print()

    print("# Audit Logging")
    print("ENABLE_AUDIT_LOGGING=true")
    print("AUDIT_ADMIN_ACTIONS_ONLY=true")
    print()

    print("# Public Access Configuration")
    print("ALLOW_PUBLIC_UPLOAD=true")
    print("REQUIRE_AUTH_FOR_RESULTS=false")
    print()

    print("# CORS Configuration")
    print("CORS_ALLOW_CREDENTIALS=true")
    print("CORS_MAX_AGE=3600")
    print()

    print("# Note: Update INITIAL_ADMIN_EMAIL with your actual email address")
    print("# Note: Keep these secrets secure and never commit them to version control")


def main():
    """Main function."""
    parser = argparse.ArgumentParser(
        description="Generate cryptographically secure secrets for DocTranslator"
    )
    parser.add_argument(
        "--type",
        choices=["jwt-key", "password", "api-key", "all"],
        default="all",
        help="Type of secret to generate",
    )
    parser.add_argument(
        "--length", type=int, default=16, help="Length for password generation (default: 16)"
    )

    args = parser.parse_args()

    print("DocTranslator Secret Generator")
    print("=" * 40)
    print()

    if args.type == "jwt-key":
        generate_jwt_key()
    elif args.type == "password":
        generate_admin_password(args.length)
    elif args.type == "api-key":
        generate_api_key()
    elif args.type == "all":
        generate_all()
    else:
        print(f"Unknown type: {args.type}")
        sys.exit(1)


if __name__ == "__main__":
    main()
